context:
  repo_owner: ${{ env.get("REPO_OWNER", default="devmatteini")}}
  repo_name: ${{ env.get("REPO_NAME", default="dra")}}
  pkg_tag: ${{ env.get("PKG_TAG", default="0.0.1") }}
  pkg_version: ${{ env.get("PKG_VERSION", default="${{ pkg_tag }}") }}
  pkg_sha256: ${{ env.get("PKG_SHA256", default="") }}

package:
  name: ${{ repo_name|lower }}
  version: ${{ pkg_version }}

source:
  url: https://github.com/${{ repo_owner }}/${{ repo_name }}/archive/refs/tags/${{ pkg_tag }}.tar.gz
  target_directory: source
  sha256: ${{ pkg_sha256 }}

build:
  number: 0
  script:
    - cd source
    - if: linux
      then: export CC=$CC
    - if: linux
      then: export CXX=$CXX
    - if: linux
      then: export LD=$LD
    - if: linux
      then: export RUSTFLAGS="-C link-arg=-Wl,--dynamic-linker=/lib64/ld-linux-x86-64.so.2"
    - cargo build --release --locked
    - mkdir -p $PREFIX/bin
    - cp target/release/${{ repo_name }} $PREFIX/bin/${{ repo_name }}

requirements:
  build:
    - rust
    - if: linux
      then: ${{ compiler('c') }}
      else: make
    - if: linux
      then: sysroot_linux-64 2.17.*