context:
  repo_owner: ${{ env.get("REPO_OWNER", default="devmatteini")}}
  repo_name: ${{ env.get("REPO_NAME", default="dra")}}
  pkg_version: ${{ env.get("PKG_VERSION", default="0.0.2") }}
  pkg_sha256: ${{ env.get("PKG_SHA256", default="") }}

package:
  name: ${{ repo_name|lower }}
  version: ${{ pkg_version }}

source:
  url: https://github.com/${{ repo_owner }}/${{ repo_name }}/archive/refs/tags/${{ pkg_version }}.tar.gz
  target_directory: source
  sha256: ${{ pkg_sha256 }}

build:
  number: 0
  script:
    - cd source
    - cargo build --release --locked
    - mkdir -p $PREFIX/bin
    - cp target/release/${{ repo_name }} $PREFIX/bin/${{ repo_name }}

requirements:
  build:
    - make
    - rust