context:
  repo_owner: ${{ env.get("REPO_OWNER", default="devmatteini")}}
  repo_name: ${{ env.get("REPO_NAME", default="dra")}}
  pkg_tag: ${{ env.get("PKG_TAG", default="0.0.1") }}
  pkg_version: ${{ env.get("PKG_VERSION", default="0.0.1") }}
  pkg_sha256: ${{ env.get("PKG_SHA256", default="") }}

package:
  name: ${{ repo_name|lower }}
  version: ${{ pkg_version }}

source:
  url: https://github.com/${{ repo_owner }}/${{ repo_name }}/archive/refs/tags/${{ pkg_tag }}.tar.gz
  target_directory: source
  sha256: ${{ pkg_sha256 }}

build:
  number: 0
  script:
    - cd source
    - export CC=$CC
    - export CXX=$CXX
    - export LD=$LD
    - export RUSTFLAGS="-C link-arg=-Wl,--dynamic-linker=/lib64/ld-linux-x86-64.so.2"
    - cargo build --release --locked
    - mkdir -p $PREFIX/bin
    - if: win
      then: cp target/release/${{ repo_name }}.exe $PREFIX/bin/${{ repo_name }}.exe
      else: cp target/release/${{ repo_name }} $PREFIX/bin/${{ repo_name }}

requirements:
  build:
    - rust
    - if: linux
      then: ${{ compiler('c') }}
      else: make
    - if: linux
      then: sysroot_linux-64 2.17